### ISSUE TITLE
crudResulter double callback

### ISSUE THREAD

**Issue by brett19** [couchbase/gocbcorex#100]
I saw the following when running the tests:
```
panic: interface conversion: interface {} is []uint8, not *memdx.BootstrapResult

goroutine 316 [running]:
github.com/couchbase/gocbcorex.kvClient_SimpleCall[...]({0x14be0f8, 0xc000307c80}, 0xc000001680, {{0x14bf3f0, 0x1716b50?}}, 0x1451ad8?, 0x132abc0)
	/Users/brettlawson/couchsdk/stellar-gateway/contrib/gocbcorex/kvclient_ops.go:79 +0x4ad
github.com/couchbase/gocbcorex.(*kvClient).bootstrap(...)
	/Users/brettlawson/couchsdk/stellar-gateway/contrib/gocbcorex/kvclient_ops.go:124
github.com/couchbase/gocbcorex.NewKvClient({0x14be0f8, 0xc000307c80}, 0xc000024af0, 0xc0000b9d60)
	/Users/brettlawson/couchsdk/stellar-gateway/contrib/gocbcorex/kvclient.go:208 +0x8cb
github.com/couchbase/gocbcorex.NewKvClientPool.func1({0x14be0f8, 0xc000307c80}, 0xc0004b2620?)
	/Users/brettlawson/couchsdk/stellar-gateway/contrib/gocbcorex/kvclientpool.go:89 +0x68
github.com/couchbase/gocbcorex.(*kvClientPool).startNewClientLocked.func1()
	/Users/brettlawson/couchsdk/stellar-gateway/contrib/gocbcorex/kvclientpool.go:199 +0xd5
created by github.com/couchbase/gocbcorex.(*kvClientPool).startNewClientLocked
	/Users/brettlawson/couchsdk/stellar-gateway/contrib/gocbcorex/kvclientpool.go:197 +0x258
FAIL	github.com/couchbase/gocbcorex	28.457s
```

**Comment by brett19** [comment]
Fix has been merged.
