### ISSUE TITLE
Panic in TestKvClientPoolClose

### ISSUE THREAD

**Issue by chvck** [couchbase/gocbcorex#144]
Seen in CI https://github.com/couchbase/gocbcorex/actions/runs/5212839493/jobs/9406987447?pr=143

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x74dc4c]

goroutine 390 [running]:
github.com/couchbase/gocbcorex.NewKvClient({0x915a18, 0xc0003a0340}, 0xc00039e2d0, 0xc000479d38)
	/home/runner/work/gocbcorex/gocbcorex/kvclient.go:263 +0xe6c
github.com/couchbase/gocbcorex.NewKvClientPool.func1({0x915a18, 0xc0003a0340}, 0x0?)
	/home/runner/work/gocbcorex/gocbcorex/kvclientpool.go:98 +0xb9
github.com/couchbase/gocbcorex.(*kvClientPool).startNewClientLocked.func1()
	/home/runner/work/gocbcorex/gocbcorex/kvclientpool.go:201 +0xd5
created by github.com/couchbase/gocbcorex.(*kvClientPool).startNewClientLocked
	/home/runner/work/gocbcorex/gocbcorex/kvclientpool.go:199 +0x278
FAIL	github.com/couchbase/gocbcorex	7.200s
?   	github.com/couchbase/gocbcorex/cbhttpx	[no test files]

**Comment by brett19** [comment]
This should be fixed by #144
